/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YdelserRouteImport } from './routes/ydelser'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as OmRouteImport } from './routes/om'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ApplikationerRouteImport } from './routes/applikationer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnruledIndexRouteImport } from './routes/unruled/index'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as UnruledTermsRouteImport } from './routes/unruled/terms'
import { Route as UnruledPrivacyRouteImport } from './routes/unruled/privacy'
import { Route as LabOrbitRouteImport } from './routes/lab/orbit'
import { Route as EnServicesRouteImport } from './routes/en/services'
import { Route as EnContactRouteImport } from './routes/en/contact'
import { Route as EnApplicationsRouteImport } from './routes/en/applications'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as ApiBookRouteImport } from './routes/api/book'

const YdelserRoute = YdelserRouteImport.update({
  id: '/ydelser',
  path: '/ydelser',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const OmRoute = OmRouteImport.update({
  id: '/om',
  path: '/om',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplikationerRoute = ApplikationerRouteImport.update({
  id: '/applikationer',
  path: '/applikationer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnruledIndexRoute = UnruledIndexRouteImport.update({
  id: '/unruled/',
  path: '/unruled/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnruledTermsRoute = UnruledTermsRouteImport.update({
  id: '/unruled/terms',
  path: '/unruled/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UnruledPrivacyRoute = UnruledPrivacyRouteImport.update({
  id: '/unruled/privacy',
  path: '/unruled/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LabOrbitRoute = LabOrbitRouteImport.update({
  id: '/lab/orbit',
  path: '/lab/orbit',
  getParentRoute: () => rootRouteImport,
} as any)
const EnServicesRoute = EnServicesRouteImport.update({
  id: '/en/services',
  path: '/en/services',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/en/contact',
  path: '/en/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnApplicationsRoute = EnApplicationsRouteImport.update({
  id: '/en/applications',
  path: '/en/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookRoute = ApiBookRouteImport.update({
  id: '/api/book',
  path: '/api/book',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applikationer': typeof ApplikationerRoute
  '/kontakt': typeof KontaktRoute
  '/om': typeof OmRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ydelser': typeof YdelserRoute
  '/api/book': typeof ApiBookRoute
  '/en/about': typeof EnAboutRoute
  '/en/applications': typeof EnApplicationsRoute
  '/en/contact': typeof EnContactRoute
  '/en/services': typeof EnServicesRoute
  '/lab/orbit': typeof LabOrbitRoute
  '/unruled/privacy': typeof UnruledPrivacyRoute
  '/unruled/terms': typeof UnruledTermsRoute
  '/en/': typeof EnIndexRoute
  '/unruled/': typeof UnruledIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applikationer': typeof ApplikationerRoute
  '/kontakt': typeof KontaktRoute
  '/om': typeof OmRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ydelser': typeof YdelserRoute
  '/api/book': typeof ApiBookRoute
  '/en/about': typeof EnAboutRoute
  '/en/applications': typeof EnApplicationsRoute
  '/en/contact': typeof EnContactRoute
  '/en/services': typeof EnServicesRoute
  '/lab/orbit': typeof LabOrbitRoute
  '/unruled/privacy': typeof UnruledPrivacyRoute
  '/unruled/terms': typeof UnruledTermsRoute
  '/en': typeof EnIndexRoute
  '/unruled': typeof UnruledIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applikationer': typeof ApplikationerRoute
  '/kontakt': typeof KontaktRoute
  '/om': typeof OmRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ydelser': typeof YdelserRoute
  '/api/book': typeof ApiBookRoute
  '/en/about': typeof EnAboutRoute
  '/en/applications': typeof EnApplicationsRoute
  '/en/contact': typeof EnContactRoute
  '/en/services': typeof EnServicesRoute
  '/lab/orbit': typeof LabOrbitRoute
  '/unruled/privacy': typeof UnruledPrivacyRoute
  '/unruled/terms': typeof UnruledTermsRoute
  '/en/': typeof EnIndexRoute
  '/unruled/': typeof UnruledIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applikationer'
    | '/kontakt'
    | '/om'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/ydelser'
    | '/api/book'
    | '/en/about'
    | '/en/applications'
    | '/en/contact'
    | '/en/services'
    | '/lab/orbit'
    | '/unruled/privacy'
    | '/unruled/terms'
    | '/en/'
    | '/unruled/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applikationer'
    | '/kontakt'
    | '/om'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/ydelser'
    | '/api/book'
    | '/en/about'
    | '/en/applications'
    | '/en/contact'
    | '/en/services'
    | '/lab/orbit'
    | '/unruled/privacy'
    | '/unruled/terms'
    | '/en'
    | '/unruled'
  id:
    | '__root__'
    | '/'
    | '/applikationer'
    | '/kontakt'
    | '/om'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/ydelser'
    | '/api/book'
    | '/en/about'
    | '/en/applications'
    | '/en/contact'
    | '/en/services'
    | '/lab/orbit'
    | '/unruled/privacy'
    | '/unruled/terms'
    | '/en/'
    | '/unruled/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplikationerRoute: typeof ApplikationerRoute
  KontaktRoute: typeof KontaktRoute
  OmRoute: typeof OmRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  YdelserRoute: typeof YdelserRoute
  ApiBookRoute: typeof ApiBookRoute
  EnAboutRoute: typeof EnAboutRoute
  EnApplicationsRoute: typeof EnApplicationsRoute
  EnContactRoute: typeof EnContactRoute
  EnServicesRoute: typeof EnServicesRoute
  LabOrbitRoute: typeof LabOrbitRoute
  UnruledPrivacyRoute: typeof UnruledPrivacyRoute
  UnruledTermsRoute: typeof UnruledTermsRoute
  EnIndexRoute: typeof EnIndexRoute
  UnruledIndexRoute: typeof UnruledIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ydelser': {
      id: '/ydelser'
      path: '/ydelser'
      fullPath: '/ydelser'
      preLoaderRoute: typeof YdelserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om': {
      id: '/om'
      path: '/om'
      fullPath: '/om'
      preLoaderRoute: typeof OmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applikationer': {
      id: '/applikationer'
      path: '/applikationer'
      fullPath: '/applikationer'
      preLoaderRoute: typeof ApplikationerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unruled/': {
      id: '/unruled/'
      path: '/unruled'
      fullPath: '/unruled/'
      preLoaderRoute: typeof UnruledIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unruled/terms': {
      id: '/unruled/terms'
      path: '/unruled/terms'
      fullPath: '/unruled/terms'
      preLoaderRoute: typeof UnruledTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unruled/privacy': {
      id: '/unruled/privacy'
      path: '/unruled/privacy'
      fullPath: '/unruled/privacy'
      preLoaderRoute: typeof UnruledPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/orbit': {
      id: '/lab/orbit'
      path: '/lab/orbit'
      fullPath: '/lab/orbit'
      preLoaderRoute: typeof LabOrbitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/services': {
      id: '/en/services'
      path: '/en/services'
      fullPath: '/en/services'
      preLoaderRoute: typeof EnServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/en/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/applications': {
      id: '/en/applications'
      path: '/en/applications'
      fullPath: '/en/applications'
      preLoaderRoute: typeof EnApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/book': {
      id: '/api/book'
      path: '/api/book'
      fullPath: '/api/book'
      preLoaderRoute: typeof ApiBookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplikationerRoute: ApplikationerRoute,
  KontaktRoute: KontaktRoute,
  OmRoute: OmRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  YdelserRoute: YdelserRoute,
  ApiBookRoute: ApiBookRoute,
  EnAboutRoute: EnAboutRoute,
  EnApplicationsRoute: EnApplicationsRoute,
  EnContactRoute: EnContactRoute,
  EnServicesRoute: EnServicesRoute,
  LabOrbitRoute: LabOrbitRoute,
  UnruledPrivacyRoute: UnruledPrivacyRoute,
  UnruledTermsRoute: UnruledTermsRoute,
  EnIndexRoute: EnIndexRoute,
  UnruledIndexRoute: UnruledIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
