/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as OmRouteImport } from './routes/om'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as YdelserRouteImport } from './routes/ydelser'
import { Route as ApiBookRouteImport } from './routes/api/book'
import { Route as LabOrbitRouteImport } from './routes/lab/orbit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const OmRoute = OmRouteImport.update({
  id: '/om',
  path: '/om',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const YdelserRoute = YdelserRouteImport.update({
  id: '/ydelser',
  path: '/ydelser',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookRoute = ApiBookRouteImport.update({
  id: '/api/book',
  path: '/api/book',
  getParentRoute: () => rootRouteImport,
} as any)
const LabOrbitRoute = LabOrbitRouteImport.update({
  id: '/lab/orbit',
  path: '/lab/orbit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/om': typeof OmRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ydelser': typeof YdelserRoute
  '/api/book': typeof ApiBookRoute
  '/lab/orbit': typeof LabOrbitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/om': typeof OmRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ydelser': typeof YdelserRoute
  '/api/book': typeof ApiBookRoute
  '/lab/orbit': typeof LabOrbitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/om': typeof OmRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ydelser': typeof YdelserRoute
  '/api/book': typeof ApiBookRoute
  '/lab/orbit': typeof LabOrbitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kontakt'
    | '/om'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/ydelser'
    | '/api/book'
    | '/lab/orbit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontakt'
    | '/om'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/ydelser'
    | '/api/book'
    | '/lab/orbit'
  id:
    | '__root__'
    | '/'
    | '/kontakt'
    | '/om'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/ydelser'
    | '/api/book'
    | '/lab/orbit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  OmRoute: typeof OmRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  YdelserRoute: typeof YdelserRoute
  ApiBookRoute: typeof ApiBookRoute
  LabOrbitRoute: typeof LabOrbitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om': {
      id: '/om'
      path: '/om'
      fullPath: '/om'
      preLoaderRoute: typeof OmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ydelser': {
      id: '/ydelser'
      path: '/ydelser'
      fullPath: '/ydelser'
      preLoaderRoute: typeof YdelserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/book': {
      id: '/api/book'
      path: '/api/book'
      fullPath: '/api/book'
      preLoaderRoute: typeof ApiBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/orbit': {
      id: '/lab/orbit'
      path: '/lab/orbit'
      fullPath: '/lab/orbit'
      preLoaderRoute: typeof LabOrbitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  OmRoute: OmRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  YdelserRoute: YdelserRoute,
  ApiBookRoute: ApiBookRoute,
  LabOrbitRoute: LabOrbitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
